# Generated by Django 4.2.30 on 2026-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_explicit_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='em_color',
            field=models.CharField(default='#e2418c', max_length=20, verbose_name='Couleur des <em> dans les titres (h2 em, .section__title em)'),
        ),
        migrations.AlterField(
            model_name='plancard',
            name='badge',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badge (ex: ⭐ Recommandé)'),
        ),
        migrations.AlterField(
            model_name='plancard',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Prix (ex: 69.9)'),
        ),
        migrations.AlterField(
            model_name='plancard',
            name='speed',
            field=models.CharField(max_length=50, verbose_name='Débit (ex: 50)'),
        ),
        migrations.AlterField(
            model_name='plancard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nom du forfait (ex: Famille connectée)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Liste des points (ex: [{"text": "..."}])'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='dark_bg',
            field=models.CharField(default='#251444', max_length=20, verbose_name='Fond sombre (header, footer, topbar)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='heading_color',
            field=models.CharField(default='#251444', max_length=20, verbose_name='Couleur des titres (h1, h2, h3…)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='light_bg',
            field=models.CharField(default='#F7F5F1', max_length=20, verbose_name='Fond clair (sections alternées)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_color',
            field=models.CharField(default='#e2418c', max_length=20, verbose_name='Couleur principale (boutons, accents)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_dark',
            field=models.CharField(default='#e08e00', max_length=20, verbose_name='Couleur principale sombre (hover)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='text_color',
            field=models.CharField(default='#737177', max_length=20, verbose_name='Couleur du texte courant'),
        ),
        migrations.AlterField(
            model_name='trustitem',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé (ex: Réseau hybride)'),
        ),
        migrations.AlterField(
            model_name='trustitem',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Valeur / Stat (ex: 5G + 4G)'),
        ),
    ]
